version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: MySecurePass
      POSTGRES_DB: midatabase
    container_name: techtestdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
